apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: server-simple-gone-com-tls
spec:
  secretName: server-simple-gone-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: serversimplegone.com
  dnsNames:
    - serversimplegone.com
    - www.serversimplegone.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - serversimplegone.com
          - www.serversimplegone.com