apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: louismbuyu17/wow-server
          ports:
            - containerPort: 5000
          env:
            - name: MONGODBURI
              valueFrom:
                secretKeyRef:
                  name: mongodburi
                  key: MONGODBURI